name: wallpaper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  open_file: ^3.3.2
  permission_handler: ^11.3.1
  image_downloader: 
    git:
      url: https://github.com/VikasTailorbird/image_downloader
  share_plus: ^7.2.2
  device_info_plus: ^9.1.2
  media_store_plus: ^0.1.2
  image_gallery_saver: ^2.0.3
  dio: ^5.4.3+1
  provider: ^6.1.2
  flutter_wallpaper_manager: ^0.0.4
  flutter_cache_manager: 
  shared_preferences: ^2.2.3
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  get: ^4.6.6




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
